
name: .NET
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '9.0.x' }
      - run: dotnet restore Nyota.sln
      - run: dotnet build Nyota.sln --configuration Release --no-restore
      - run: dotnet test Nyota.sln --no-build --verbosity normal
